name: Use Workflow

on:
  workflow_dispatch:

jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
        - name: echo something
          run: |
            echo "Let's see if it works"
    workflow:
      needs: job1
      if: ${{ !cancelled() }}
      uses: ./.github/workflows/generate-ascii.yaml
      secrets: inherit